#+TITLE: The Eye of Modernism:
#+SUBTITLE: Visualities of British Literature, 1880—1930
#+AUTHOR: Jonathan Reeve

* Abstract

British fiction and poetry explodes with textual visuality in the early twentieth century: color, shape, and form, as manifested in description, impression, and image. This dissertation computationally models that visuality, using the eye as a governing metaphor: retinal cones are modeled by inferring textual color, and retinal rods are modeled through object-detection via word sense disambiguation and categorization. Findings include a 93% increase in color expressions across the nineteenth and early twentieth centuries, a 15% increase in the proportions of object and artifacts, and revealing correlations along lines of literary genre, subject heading, and more. These correlate with historical materialities such a dye manufacture, trends in the visual arts such as post-impressionism, and movements in literature such as imagism. A model of literary description, meanwhile, finds that, while visuality increases over time, proportions of description decrease, suggesting structural decompositions in fiction, occurring in parallel with disseminations of vision.  

This dissertation is a full-color, interactive document, originally formatted in HTML, and made freely available on the Internet. It contains interactive plots, hyperlinks, and other dynamic elements. It is a social document, annotated by the community, and open for further annotation. If you are reading this in another document format (PDF, DOCX, or paper), you are missing these social, interactive, and dynamic elements. Please visit [[https://dissertation.jonreeve.com/][dissertation.jonreeve.com]] for the canonical edition of this text, and [[https://github.com/JonathanReeve/dissertation][github.com/JonathanReeve/dissertation]] for its source code.

* Table of Contents

- [[./00-introduction/introduction-v01.html][Introduction]] 
- [[./01-colors/ch-1-v01.html][Chapter 1: Color]] 
- [[./02-shapes/ch-2-v01.html][Chapter 2: Shape]] 
- [[./03-images/ch-3-v01.html][Chapter 3: Image]] 
  
* List of Charts, Graphs, Illustrations

#+INCLUDE: "templates/figures.html" export html

* Acknowledgments

This dissertation would not have been possible without the advice and support of a large network of scholars, at Columbia University and elsewhere. I'd like to thank my dissertation committee: Sarah Cole, Matthew Hart, and Dennis Tenen; the Literary Modeling and Visualization Lab, and the Group for Experimental Methods in the Humanities at Columbia University; Explosion AI, who generously donated a research license to Prodigy, their proprietary human-in-the-loop AI model training software; and the members of the 20/21st Century Colloquium at Columbia University, who provided useful feedback on early drafts of the first chapter.
