#+TITLE: The Eye of Modernism:
#+SUBTITLE: Visualities of British Literature, 1880—1930
#+AUTHOR: Jonathan Reeve

**WARNING**: This is a preview of my dissertation, and represents its current state, which is very much a work-in-progress.

* Abstract

Abstract here.

* Table of Contents

- [[./00-introduction/introduction.html][Introduction]]
- [[./01-colors/ch-1.html][Chapter 1: Color]]
- [[./02-shapes/ch-2.html][Chapter 2: Shapes, Bodies, Objects]]
- [[./03-images/ch-3.html][Chapter 3: Image]]

* List of Charts, Graphs, Illustrations

#+INCLUDE: "templates/figures.html" export html

* Acknowledgments

This dissertation would not have been possible without the advice and support of a large network of scholars, at Columbia University and elsewhere. I'd like to thank my dissertation committee: Sarah Cole, Matthew Hart, and Dennis Tenen; the Literary Modeling and Visualization Lab, and the Group for Experimental Methods in the Humanities at Columbia University; Explosion AI, who generously donated a research license to Prodigy, their proprietary human-in-the-loop AI model training software; and the members of the 20/21st Century Colloquium at Columbia University, who provided useful feedback on early drafts of the first chapter.
