#+TITLE: The Eye of Modernism:
#+SUBTITLE: Visualities of British Literature, 1880—1930
#+AUTHOR: Jonathan Reeve

* Abstract

British fiction and poetry of the early twentieth century sees an explosion of textual visuality: color, shape, and form, as manifested in description, impression, and other literary functions. This dissertation computationally models that visuality, using the eye as a governing metaphor: retinal cones are modeled by inferring textual color, and retinal rods are modeled through object-detection via word sense disambiguation and categorization. Findings include a 93% increase in color expressions across the nineteenth and early twentieth centuries, a 15% increase in object and artifacts, and revealing correlations along lines of literary genre, subject heading, and more. These correlate with historical materialities such a dye manufacture, trends in the visual arts such as post-impressionism, and movements in literature such as imagism. Negative correlations

* Table of Contents

- [[./00-introduction/introduction.html][Introduction]]
- [[./01-colors/ch-1.html][Chapter 1: Color]]
- [[./02-shapes/ch-2.html][Chapter 2: Shapes, Bodies, Objects]]
- [[./03-images/ch-3.html][Chapter 3: Image]]

* List of Charts, Graphs, Illustrations

#+INCLUDE: "templates/figures.html" export html

* Acknowledgments

This dissertation would not have been possible without the advice and support of a large network of scholars, at Columbia University and elsewhere. I'd like to thank my dissertation committee: Sarah Cole, Matthew Hart, and Dennis Tenen; the Literary Modeling and Visualization Lab, and the Group for Experimental Methods in the Humanities at Columbia University; Explosion AI, who generously donated a research license to Prodigy, their proprietary human-in-the-loop AI model training software; and the members of the 20/21st Century Colloquium at Columbia University, who provided useful feedback on early drafts of the first chapter.
