#+TITLE: Introduction
#+AUTHOR: Jonathan Reeve

The central question of this dissertation is one of literary history. It's one of how we get from point A to point B. Consider this passage from Jane Austen's /Pride and Prejudice/ to be point A:

#+begin_quote
At length the Parsonage was discernible. The garden sloping to the road, the house standing in it, the green pales and the laurel hedge, every thing declared they were arriving. Mr. Collins and Charlotte appeared at the door, and the carriage stopped at the small gate, which led by a short gravel walk to the house, amidst the nods and smiles of the whole party. In a moment they were all out of the chaise, rejoicing at the sight of each other. Mrs. Collins welcomed her friend with the liveliest pleasure, and Elizabeth was more and more satisfied with coming, when she found herself so affectionately received. She saw instantly that her cousin's manners were not altered by his marriage; his formal civility was just what it had been, and he detained her some minutes at the gate to hear and satisfy his enquiries after all her family. They were then, with no other delay than his pointing out the neatness of the entrance, taken into the house; and as soon as they were in the parlour, he welcomed them a second time with ostentatious formality to his humble abode, and punctually repeated all his wife's offers of refreshment.
#+end_quote

And this passage from Virginia Woolf's /To the Lighthouse/ to be point B:

#+begin_quote
The jacmanna was bright violet; the wall staring white. She would not have considered it honest to tamper with the bright violet and the staring white, since she saw them like that, fashionable though it was, since Mr. Paunceforte's visit, to see everything pale, elegant, semitransparent. Then beneath the colour there was the shape. She could see it all so clearly, so commandingly, when she looked: it was when she took her brush in hand that the whole thing changed. It was in that moment's flight between the picture and her canvas that the demons set on her who often brought her to the verge of tears and made this passage from conception to work as dreadful as any down a dark passage for a child. Such she often felt herself—struggling against terrific odds to maintain her courage; to say: "But this is what I see; this is what I see," and so to clasp some miserable remnant of her vision to her breast, which a thousand forces did their best to pluck from her.
#+end_quote

The Austen passage is one of her most descriptive: full of objects and visualities, yet with images that are nonetheless subordinated to the narrative.

In contrast, Woolf's descriptive passage is thickly indulgent in its visuality.

There is nothing quite as reductive as chronology, it must be conceded.

By juxtaposing two paragraphs as historical artifacts, we are missing that A belongs to a certain romance genre, while B belongs to an artist-novel genre, in which aesthetic choices and visuality are necessarily foregrounded.

* Technologies

A number of software programs were prepared for this project, written in Python, Haskell, and using shell scripting languages.

** The text itself

I made the unconventional decision to write this dissertation in HTML, rather than produce a Microsoft Word document or a PDF file. Since Word and PDF were created as proprietary formats, developed by Microsoft and Adobe, they were made to sell software, rather than contribute to the community. Furthermore, they are made to mimic the paper office, using a virtual 8.5 by 11 inch "page." Since this dissertation will not be printed, this constraint is unnecessary. HTML, on the other hand, is much more featureful markup language, allowing for interactive charts, hyperlinks, variable page width, and much, much more. Since it it always-already published on the Internet, it is much more easily archivable, readable with a wider variety of reading software (web browsers), and provides a more seamless experience for those using screen readers or other accessibility software.

This text is originally written in a feature-rich markup language called [[https://orgmode.org/][Org]], which compiles to HTML

The text of the dissertation text itself contains a number of innovations:

 - A [[https://github.com/JonathanReeve/dissertation/blob/master/Shakefile.hs][Shakefile]] written in Haskell, for the [[https://shakebuild.com/][Shake build system]], which interfaces with Pandoc to convert plain text files to HTML, which I originally wrote in [[https://orgmode.org/][the org-mode text format]].
 - [[https://github.com/JonathanReeve/dissertation/blob/master/Template.hs][A template]] written in [[https://chrisdone.com/posts/lucid/][Lucid]] and [[http://fvisser.nl/clay/][Clay]], Haskell domain-specific languages for HTML and CSS, which integrates [[https://edwardtufte.github.io/tufte-css/][Tufte-CSS]], [[https://mermaid-js.github.io/mermaid/#/][Mermaid]] diagram capability, and more.
 - Custom Pandoc filters, written in Haskell: [[https://github.com/JonathanReeve/dissertation/blob/master/templates/hexFilter.hs][one for displaying color hex values]], used in Chapter 1, and [[https://github.com/JonathanReeve/dissertation/blob/master/templates/synsetFilter.hs][one for displaying WordNet synsets]], used in Chapter 2.


This technological stack has been abstracted into the template project [[https://github.com/JonathanReeve/template-dissertation][template-dissertation]], a standards-focused, HTML-first dissertation build system.

** Submodules
- color-word-analyzer: a CLI program and web app to analyze color in a text
- custom-ngrams-search: a framework for searching Google NGrams data for custom textual patterns
- count-objects: software for counting objects in literary texts, using word sense disambiguation
- description-detection: a program for probabilistically detecting literary description

* Corpus
